## <center>Основы математического языка: кванторы</center>

Познакомимся с **кванторами** и символами, позволяющими записывать математические формулировки:

* Символ $\forall$ читается как «для любого» и называется **квантором всеобщности**. Он заменяет собой слова «любой», «всякий», «для любого» и т. п.

* Символ $\exists$ читается как «существует» и называется **квантором существования**, а $\exists !$ читается как «существует единственный» и называется **квантором существования и единственности**.   заменяет слова «существует», «найдётся» и т. п.

* Знак импликации $\rightarrow$ (или $\Rightarrow$) воспринимается как замена слов «следует», «влечёт», «вытекает», «имеет место», «выполняется».

* Знак равносильности или эквивалентности $\leftrightarrow$ (или $\Leftrightarrow$) заменяет словосочетания «тогда и только тогда, когда», «в том и только том случае, когда», «если и только если».

* Двоеточие $:$ в математических формулах читается как «такой, что».

* Вертикальная черта $|$ означает «при условии, что».

# <center>Основные понятия линейной алгебры: векторы</center>

Наиболее общее определение, которое подойдёт ко всем случаям: **Вектор** — это набор чисел, записанных в определённом порядке (в столбец или в строку).

$$\overrightarrow{s}=(s_1, s_2, ..., s_m)$$

$$\overrightarrow{s}=\left( \begin{array}{c} s_1 \\ s_2 \\ \dots \\ s_m \end{array} \right)$$

Числа $s_1, s_2, ..., s_m$ называются **координатами вектора**, а количество этих координат ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=m$ называется **размерностью вектора**.

In [1]:
import numpy as np

In [2]:
# Задаём вектор как одномерный массив numpy с помощью функции np.array
s = np.array([33, 64, 50, 45])
s

array([33, 64, 50, 45])

In [3]:
# Находим третью координату
s[2]

50

In [4]:
# Находим размерность вектора
len(s)

4

Длина трёхмерного вектора $\overrightarrow{s}$ определяется аналогично двухмерному:

$$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+{\left(s_3\right)}^2}$$

> В общем случае вектор $\overrightarrow{\boldsymbol{s}}\boldsymbol{=(}{\boldsymbol{s}}_{\boldsymbol{1}}\boldsymbol{,\ }{\boldsymbol{s}}_{\boldsymbol{2}}\boldsymbol{,\ \dots ,\ }{\boldsymbol{s}}_{\boldsymbol{m}}\boldsymbol{)}$ размерностью ${\boldsymbol{dim} \left(\overrightarrow{\boldsymbol{s}}\right)\ }\boldsymbol{=}\boldsymbol{m}$ задаёт в векторном $m$-мерном пространстве $\boldsymbol{S}\boldsymbol{\subset }{\mathbb{R}}^{\boldsymbol{m}}$ направленный отрезок с началом в точке $O=(0,0,…,0)$ и концом в точке $(s_1,s_2,…,s_m)$. 

Длина такого вектора $\overrightarrow{s}$ будет вычисляться так:

$$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+\dots +{\left(s_m\right)}^2}=\sqrt{\sum^m_{j=1}{{\left(s_j\right)}^2}}$$

## <center>Базовые операции с векторами</center>

Сложение и вычитание векторов в *Python* происходит при помощи знаков + и -. Причём важно задать векторы именно как массивы *numpy*, а не как обычные списки типа *list*.

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [6]:
a + b

array([15, 23, 14,  8])

In [7]:
a - b

array([ 5, -7, -4, -6])

Пусть задан вектор ${\overrightarrow{v}}_1$ из векторного пространства $V\subset {\mathbb{R}}^m$:

$$\overrightarrow{v_1}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)$$

Тогда результатом умножения векторов ${\overrightarrow{v}}_1$ на число $\omega \in \mathbb{R}$ называется новый вектор ${\overrightarrow{v}}_2$, принадлежащий тому же векторному пространству $V$, с координатами:

$$\overrightarrow{v_2}=\omega \overrightarrow{v_1}=\omega \left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)=\left( \begin{array}{c} \omega v_{11} \\ \omega v_{12} \\ \dots \\ \omega v_{1m} \end{array} \right)$$

> Векторы ${\overrightarrow{v}}_1$ и ${\overrightarrow{v}}_2$ пропорциональны друг другу с коэффициентом $\omega$. По-другому такие векторы называются коллинеарными. Обозначается: ${\overrightarrow{v}}_1||\overrightarrow{v_2}$.

Если коэффициент пропорциональности положительный ($\omega >0$), векторы сонаправлены (смотрят в одном направлении), если отрицательный ($\omega <0$) — противоположно направлены. Геометрически это значит, что векторы лежат на одной прямой (или параллельных прямых) и направлены в одну или противоположные стороны.

В *Python* число умножается на массив numpy обычным оператором умножения.

In [8]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

> **Примечание о разнице векторов**. В строгой линейной алгебре нет такой отдельной операции, как разница векторов. Под разницей двух векторов $\overrightarrow{v_2}$ и $\overrightarrow{v_1}$ понимается сложение векторов $\overrightarrow{v_2}$ и $(-1)\overrightarrow{v_1}$.

> Геометрически умножить вектор на скаляр означает изменить его длину в $\alpha$ раз. Если $|\alpha |>1$, то длина вектора пропорционально увеличивается. Если $|\alpha |<1$, то длина вектора уменьшается. Если $\alpha$ — положительное число ($\alpha>0$), то вектор сохраняет своё направление. Если $\alpha$ — отрицательное число ($\alpha<0$), то вектор меняет своё направление на противоположное.

## <center>Линейная комбинация векторов</center>

**Линейная комбинация** — это объединение операций сложения векторов и умножения на скаляр в одну. Каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются.

В *Python* линейная комбинация полностью соответствует своему названию и вычисляется как комбинация сложения векторов и умножения вектора на число.

In [9]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

Самое интересное в линейных комбинациях — это особые случаи, а именно **нулевая линейная комбинация**. Линейная комбинация векторов называется нулевой, если результат линейной комбинации равен нулевому вектору.

Как получить нулевой вектор из линейной комбинации? Самый простой вариант — чтобы все коэффициенты линейной комбинации были равны 0. Однако такой случай, называемый **тривиальным**, нам не интересен.

Нулевая линейная комбинация называется **нетривиальной**, если хотя бы один из коэффициентов отличен от 0.

Предположим, что нам удалось составить нетривиальную комбинацию, то есть удалось подобрать такие ${\omega }_i\neq 0$, что вектор $\overrightarrow{u}=\overrightarrow{0}$.

В таком случае векторы, из которых была составлена линейная комбинация $\overrightarrow{v_1},\ \overrightarrow{v_2},\ \dots ,\ \overrightarrow{v_n}$, называются **линейно зависимыми**.

Тогда хотя бы один из векторов, но не обязательно любой, в линейной комбинации можно выразить через другие векторы, представив его как линейную комбинацию.

Или же, возможно, как мы ни старались, но нам не удалось подобрать такие коэффициенты ${\omega }_i\neq 0$, чтобы составить нулевую нетривиальную линейную комбинацию. Такие векторы называются **линейно независимыми**. В таком случае ни один из векторов не выражается через другие векторы.

## <center>Скалярное произведение векторов</center>

Существует четыре способа умножить векторы между собой:

* Скалярное произведение. Результат — число. 
* Векторное произведение. Результат — вектор.
* Смешанное произведение. Результат — число. 
* Тензорное произведение. Результат — матрица.

Мы рассмотрим скалярное произведение.

Чтобы найти **скалярное произведение двух векторов**, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится.  

В *Python* скалярное произведение векторов вычисляется при помощи функции `np.dot()`:

In [10]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

Через скалярное произведение можно выразить длину вектора (обозначается как $\left|\overrightarrow{v}\right|$ или $|\left|\overrightarrow{v}\right||$).

В линейной алгебре **длина вектора** определяется как квадратный корень из скалярного произведения вектора с самим собой.

Длина вектора всегда неотрицательна и показывает, как близок вектор к нулевому.

Скалярное произведение — это не просто удобная форма записи умножения векторов. На самом деле скалярное произведение обладает рядом очень полезных **свойств**.

1) Линейность.

2) Скалярное произведение двух векторов $\overrightarrow{v_1}$ и $\overrightarrow{v_2}$ в точности равно произведению длин этих векторов $\left|\overrightarrow{v_1}\mathrm{\ }\right|$ и $\left|\overrightarrow{v_2}\mathrm{\ }\right|$ на косинус угла между ними $\mathrm{cos}\mathrm{}(\overrightarrow{v_1},\ \overrightarrow{v_2})$.

3) Из последнего свойства следует ещё одно свойство скалярного произведения. Если скалярное произведение двух векторов равно 0, то вектора ортогональны (находятся под углом 90°). И наоборот: если вектора ортогональны друг другу, их скалярное произведение равно 0.

## <center>Векторная запись линейной регрессии</center>

$$\hat{y}={\omega }_0+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$$

Давайте добавим коэффициент 1 перед параметром $\omega_0$:

$$\hat{y}={\omega }_01+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$$

А теперь представим параметры модели в виде вектора $\overrightarrow{\omega }$ и признаки — в виде вектора $\overrightarrow{x}$:

$$\overrightarrow{\omega }=\left( \begin{array}{c} {\omega }_0 \\ {\omega }_1 \\ {\omega }_2 \\ \dots \\ {\omega }_m \end{array} \right)\ \textrm{и}\ \overrightarrow{x}=\left( \begin{array}{c} 1 \\ x_1 \\ x_2 \\ \dots \\ x_m \end{array} \right)$$

Тогда уравнение линейной регрессии можно записать в лаконичной векторной форме скалярного произведения двух векторов $\overrightarrow{\omega }$ и $\overrightarrow{x}$:

$$\hat{y}=\overrightarrow{\omega }\cdot \overrightarrow{x}$$

Возник вопрос: как ищутся коэффициенты линейной комбинации ${\omega }_1$ и ${\omega }_2$? Не искать же их полным перебором.

На этот вопрос в своё время ответил Гаусс и создал знакомый нам **метод наименьших квадратов (МНК)**, который мы уже многократно использовали в модулях по машинному обучению. Но, чтобы познакомиться с МНК поближе с математической точки зрения, нам с вами необходимо изучить тему матриц и матричных преобразований.

В блокноте *"extra"* мы рассматриваем пример нормирования вектора. Интуитивно нормирование можно объяснить так ↓

**Нормирование вектора** — это получение вектора с тем же направлением, что и исходный, но с нормой 1.

Норма вектора вычисляется как корень из суммы квадратов его компонент. Её физический смысл: норма показывает, насколько вектор «большой».

**Длина вектора** (в физическом смысле) — это то же, что и норма, применимо к векторам в реальном пространстве.

> Нормирование производится делением вектора на его норму.

In [11]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [12]:
# Задание 3.3

Hut_Paradise_values = Hut_Paradise_DF.values

In [13]:
print('vektor for apartment 5:', Hut_Paradise_values[4])

vektor for apartment 5: [40 33  1  6 20 16]


In [14]:
# Задание 3.4

print('vektor for floors:', Hut_Paradise_values[:,3])

vektor for floors: [ 5 12 10  3  6 13  8 21  5]


In [15]:
# Задание 3.5

unliv_area = Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]
print('vektor for unliv.area:', unliv_area)

vektor for unliv.area: [13 12 15 13 17  9 20 15 25]


In [16]:
# Задание 3.6

time = np.array([10,20,30,15,5,40,20,8,20])
print(Hut_Paradise_values[:,4] @ time)

1348


In [17]:
# Задание 3.7

u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [18]:
c=2*v-3*w
print(c)

[-3 14  3  4  2]


# <center>Матрицы</center>

**Матрица** — это структура, представляющая собой таблицу, состоящую из чисел, расположенных по строкам и столбцам.

> Математики не любят громоздкую запись, поэтому, чтобы обозначить, что матрица состоит из чисел $a_{ij}$, нередко пишут следующим образом: $A=\left(a_{ij}\right),\ \ a_{ij}\in \mathbb{R}\mathrm{,}\mathrm{\ }i=1,\ 2,\dots ,n \textit{ } j=1,\ 2,\dots ,m$.

> **Элементами главной диагонали** называются элементы, у которых индексы строк и столбцов совпадают, то есть $a_{ij}, \  i=j$.

Матрицу можно создать функцией `np.matrix()` или `np.array()`. Разницу между двумя этими способами мы обсудим в скринкасте.

За размер матрицы отвечает атрибут `shape`. 

Матрицы, как и массивы, индексируются с 0, а не с 1.

In [19]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [20]:
A.shape

(4, 3)

In [21]:
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])

a_23= 1 a_32= 3 a_33= 1


## <center>Классификация матриц</center>

Матрицы различаются по форме и по содержанию.

* **Прямоугольные матрицы** — это матрицы, у которых количество строк $n$ не совпадает с количеством столбцов $m$, т. е. $n\neq m$.
    * высокие
    * длинные

* **Квадратные матрицы** — это матрицы, у которых количество строк $n$ совпадает с количеством столбцов $m$, т. е. $n= m$. **Порядком** квадратной матрицы называется количество строк (и столбцов соответственно) в ней.

* **Вектор-столбец** — это матрица размера $(n,1)$.

* **Вектор-строка** — это матрица размера $(1,m)$.

* **Нулевая матрица** — это матрица, у которой все элементы являются нулём. Формально это записывается как $A=\left(a_{ij}\right),\ {\forall a}_{ij}=0$.

* **Матрица-единица**, или **матрица единиц** — это матрица, у которой все элементы являются единицей. Формальная запись: $A=\left(a_{ij}\right),\ {\forall a}_{ij}=1$.

> Виды матриц, о которых пойдёт речь далее, бывают только квадратными.

* **Треугольная матрица** — это квадратная матрица, у которой элементы выше или ниже главной диагонали равны 0.

    * Нижнетреугольная матрица: $A=\left(a_{i j}\right)=\left\{\begin{array}{l} a_{i j} \neq 0, \text { при } i \geq j \\ a_{i j}=0, \text { при } i<j \end{array}\right.$

    * Верхнетреугольная матрица: $A=\left(a_{i j}\right)=\left\{\begin{array}{l} a_{i j}=0, \text { при } i \geq j \\ a_{i j} \neq 0, \text { при } i<j \end{array}\right.$

* **Симметричная матрица** — это квадратная матрица, у которой элементы равны друг другу относительно главной диагонали. Формально записывается как: $S=\left(s_{ij}\right),{\ s}_{ij}={\ s}_{ji}\ \forall i,\ j$.

> Симметричные матрицы — это очень важный вид матриц. Например, матрица корреляций, с которой мы с вами уже множество раз сталкивались, является симметричной: по её диагонали находятся единицы — корреляции признаков с самими собой, а в остальных ячейках — коэффициенты корреляции.

* **Диагональная матрица** — это симметричная матрица, у которой вне главной диагонали стоят нули. Формально записывается как: 

$$S=\left(s_{ij}\right)=\left\{ \begin{array}{c} s_{ij}={\ s}_{ji}=0,\ \textrm{п}\textrm{р}\textrm{и}\ i\neq j \\ s_{ij}\neq 0,\ \textrm{п}\textrm{р}\textrm{и}\ i=j \end{array} \right.$$

У диагональной матрицы есть ещё одно обозначение: $S=diag({\alpha }_1,\ {\alpha }_2,\ \dots ,\ {\alpha }_n),$ где $\alpha_i$ — элементы, стоящие на главной диагонали.

* **Скалярная, или шаровая матрица** — это диагональная матрица, у которой по диагонали стоит одно и тоже число.

$$S=\left(s_{ij}\right)=\left\{ \begin{array}{c} s_{ij}=0,\ \textrm{п}\textrm{р}\textrm{и}\ i\neq j \\ s_{ij}=\alpha ,\ \textrm{п}\textrm{р}\textrm{и}\ i=j \end{array} \right.$$

Альтернативная запись: $S=diag(\alpha )$.

* **Единичная** (не путать с матрицей единиц!) **матрица** — это скалярная матрица, у которой $\alpha=1$. Единичная матрица является настолько важной в линейной алгебре, что даже имеет собственное специальное обозначение — латинская буква $E$.

$$E=\left(e_{ij}\right)=\left\{ \begin{array}{c} e_{ij}=0,\ \textrm{п}\textrm{р}\textrm{и}\ i\neq j \\ e_{ij}=1,\ \textrm{п}\textrm{р}\textrm{и}\ i=j \end{array} \right.$$

## <center>Базовые действия над матрицами</center>

К базовым относятся следующие операции:

* Сложение матриц. Результат — матрица.
* Умножение матрицы на число. Результат —  матрица.
* Транспонирование. Результат —  матрица.

**Операция транспонирования** — это матричная операция, при которой строки и столбцы меняются местами. Двойное транспонирование матрицы возвращает её к первичному виду. 

> Симметричные матрицы инварианты к операции транспонирования, то есть не изменяются.

> Матрица $A$ называется симметричной, если она не меняется при транспонировании, т. е. $A=A^T$.

*Смотри ноутбук "extra_2"*

In [22]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [23]:
# Задание 5.1

Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
print(Inc[0,0], Inc[1,1], Inc[2,2])

100 200 100


In [24]:
# Задание 5.2

Cons=np.array([Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption]).T
print(Cons[0,0], Cons[1,1], Cons[2,2])

50 80 140


In [25]:
# Задание 5.3

New_Inc=Inc*0.87
New_Inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [26]:
# Задание 5.4

P=New_Inc-Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

## <center>Продвинутые операции с матрицами</center>

**<u>Произведение двух матриц</u>**

Пусть заданы две матрицы $A=(a_{ij})$ и $B=(b_{ij})$, причём их размерности: ${\mathrm{dim} \left(A\right)\ }=\left(n,\ m\right)$ и ${\mathrm{dim} \left(B\right)\ }=\left(m,\ l\right)$. Произведением матриц $A$ и $B$ называется матрица $C=(c_{ij})$ размером ${\mathrm{dim} \left(C\right)\ }=\left(n,\ l\right)$ (обратите внимание на размерность), элемент которой, находящийся на пересечении $i$-й строки и $j$-го столбца, равен сумме произведений элементов $i$-й строки матрицы $A$ на соответствующие (по порядку) элементы $j$-го столбца матрицы $B$.

> Умножить матрицу $A$ на матрицу $B$ можно только в том случае, если количество столбцов в матрице $A$ совпадает с количеством строк в матрице $B$.

> Матричное умножение не перестановочно (не коммутативно). То есть перемена мест сомножителей может привести к различным результатам и даже размерностям.

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/a3a6c30c0321475ea48b8488901278cb/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_1.png)

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/163cf195ac716a3f449273547ac0081d/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_2.png)

В *Python* матрицы можно умножить с помощью функции `np.dot()`. При перемене мест сомножителей результат также меняется.

In [27]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [28]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [29]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [30]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [31]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

Произведение квадратных матриц существует, когда порядок обеих матриц совпадает. Причём результатом умножения квадратных матриц будет квадратная матрица того же порядка, что и исходные.

Например, матрицу 3х3 можно умножить только на матрицу 3х3, но нельзя на матрицу 3х4 или 4х3 или, тем более, 11х23.

**<u>Произведение матрицы и вектора</u>**

Так как вектор — это частный случай матрицы размерностью $(1,m)$ или $(n,1)$, то такое умножение полностью подчиняется правилам, которые мы ввели ранее. По определению произведения матриц результатом умножения матрицы на вектор всегда получается вектор той же размерности, что и исходный.

> Вектор-столбец умножается на матрицу справа, а вектор-строка — слева.

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/2b37a2cf3d333dc0a60dfba2f15fd31c/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_5.png)

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/c75fa4bc4a25adf76fdca272a088fcbc/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_6.png)

**<u>Тензорное произведение векторов</u>**

**Тензорное произведение** — это результат матричного умножения вектора-столбца на вектор-строку. Результатом тензорного произведения является матрица.

Размерности векторов, участвующих в умножении, составляют ${\mathrm{dim} \left(\overrightarrow{v}\right)\ }=(3,1)$ и ${\mathrm{dim} \left({\overrightarrow{u}}^T\right)\ }=(1,3)$. В результате у нас должна получиться матрица 3x3.

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/6af692dc1c836c797a52843d4bfdcb35/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_7.png)

У тензорного произведения есть специальное обозначение — $\otimes$:

$$\overrightarrow{v}\otimes \overrightarrow{u}=\left( \begin{array}{ccc} 4 & 5 & 6 \\ 8 & 10 & 12 \\ 12 & 15 & 18 \end{array} \right)$$

> В случае скалярного произведения векторов всегда получается число, а в случае тензорного — матрица.

## <center>Геометрическая интерпретация умножения матрицы на вектор</center>

Пусть у нас есть некоторая матрица $L$ размерностью ${\mathrm{dim} \left(L\right)\ }=(2, 2)$:

$$L=\left( \begin{array}{cc} 1 & 0 \\ -2 & 1 \end{array} \right)$$

И два вектора-столбца ${\overrightarrow{v}}_1={\left(3,\ 4\right)}^T$ и ${\overrightarrow{v}}_2={\left(-2,\ 1\right)}^T$.

Умножим матрицу на векторы, получим новые векторы, назовём их ${\overrightarrow{u}}_1$ и ${\overrightarrow{u}}_2$:

$${\overrightarrow{u}}_1=L{\overrightarrow{v}}_1=\left( \begin{array}{cc} 1 & 0 \\ -2 & 1 \end{array} \right)\left( \begin{array}{c} 3 \\ 4 \end{array} \right)=\left( \begin{array}{c} 1\cdot 3+0\cdot 4 \\ (-2)\cdot 3+1\cdot 4 \end{array} \right)=\left( \begin{array}{c} 3 \\ -2 \end{array} \right)$$

$${\overrightarrow{u}}_2=L{\overrightarrow{v}}_2=\left( \begin{array}{cc} 1 & 0 \\ -2 & 1 \end{array} \right)\left( \begin{array}{c} -2 \\ 1 \end{array} \right)=\left( \begin{array}{c} 1\cdot \left(-2\right)+0\cdot 1 \\ (-2)\cdot (-2)+1\cdot 1 \end{array} \right)=\left( \begin{array}{c} -2 \\ 5 \end{array} \right)$$

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/1256d721de1742d0a84616a0d8b84417/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_10.png)

После умножения матрицы на каждый из векторов мы получили новые векторы ${\overrightarrow{u}}_1$ и ${\overrightarrow{u}}_2$, причём первая координата векторов не изменилась, а вот вторая как-то образом поменялась. То есть матрица $L$ каким-то образом воздействовала на векторное пространство $V$, в котором находились векторы ${\overrightarrow{v}}_1$ и ${\overrightarrow{v}}_2$, и видоизменила исходные векторы.

> Говорят: матрица $L$ задаёт линейный оператор, который действует в векторном пространстве $V$ и переводит векторы в новое векторное пространство $U$.

Отметим два интересных частных случая **операторов**, которые активно используются в обработке изображений.

* **Оператор сжатия/растяжения:**

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/2bda26c2894a23d8ea0102d681f85983/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_11.png)

$$L=\left( \begin{array}{cc} \alpha & 0 \\ 0 & \beta \end{array} \right),$$

где где $\alpha$ и $\beta$ — коэффициенты сжатия/растяжения пространства по вертикальной и горизонтальной оси соответственно.

$$L=\left( \begin{array}{cc} \frac{2}{3} & 0 \\ 0 & \frac{3}{2} \end{array} \right)$$

$$\overrightarrow{v}={\left(3,\ 4\right)}^T$$

$$\overrightarrow{u}=L\overrightarrow{v}=\left( \begin{array}{cc} \frac{2}{3} & 0 \\ 0 & \frac{3}{2} \end{array} \right)\left( \begin{array}{c} 3 \\ 4 \end{array} \right)=\left( \begin{array}{c} 2 \\ 6 \end{array} \right)$$

Данный оператор $L$ задаёт сжатие по вертикальной оси в $\frac{2}{3}$ раза и растяжение по горизонтальной в $\frac{3}{2}$ раза.

* **Оператор поворота:**

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/ceecfca0ba4c1f02a03065249bc02617/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_12.png)

$$L=\left( \begin{array}{cc} \mathrm{cos}\mathrm{}(\alpha ) & -\mathrm{sin}\mathrm{}(\alpha \mathrm{)} \\ \mathrm{sin}\mathrm{}(\alpha \mathrm{)} & \mathrm{cos}\mathrm{}(\alpha ) \end{array} \right)$$

Данный оператор задаёт поворот пространства на угол $\alpha$. Например, поворот на угол 90°:

$$L=\left( \begin{array}{cc} \mathrm{cos}\mathrm{}(\mathrm{90}{}^\circ ) & -\mathrm{sin}\mathrm{}(\mathrm{90}{}^\circ \mathrm{)} \\ \mathrm{sin}\mathrm{}(\mathrm{90}{}^\circ \mathrm{)} & \mathrm{cos}\mathrm{}(\mathrm{90}{}^\circ ) \end{array} \right)=\left( \begin{array}{cc} 0 & -1 \\ \mathrm{1} & 0 \end{array} \right)$$

$$\overrightarrow{v}={\left(3,\ 4\right)}^T$$

$$\overrightarrow{u}=L\overrightarrow{v}=\left( \begin{array}{cc} 0 & -1 \\ \mathrm{1} & 0 \end{array} \right)\left( \begin{array}{c} 3 \\ 4 \end{array} \right)=\left( \begin{array}{c} 0\cdot 3-1\cdot 4 \\ 1\cdot 3+0\cdot 4 \end{array} \right)=\left( \begin{array}{c} -4 \\ 3 \end{array} \right)$$

Проверим скалярное произведение. Помним, что для ортогональных векторов оно должно быть равно 0:

$$\left(\overrightarrow{u},\ \overrightarrow{v}\right)=3\cdot \left(-4\right)+4\cdot 3=0$$

Векторы действительно ортогональны.

## <center>Умножение на специальные матрицы</center>

**<u>Умножение на нулевую матрицу</u>**

Нулевая матрица играет роль нуля как в матричном сложении, так и матричном умножении. То есть при умножении на нулевую матрицу мы всегда получим нулевую матрицу того же размера, что и исходная. Причём неважно, с какой стороны происходит умножение.

**<u>Умножение на единичную матрицу</u>**

Единичная матрица играет роль единицы в матричном умножении. При умножении на неё исходная матрица остаётся неизменной. Причём умножение на единичную матрицу перестановочно: порядок не играет роли (можете проверить это самостоятельно).

**<u>Умножение на шаровую матрицу</u>**

Умножение любой матрицы на шаровую матрицу с элементом $\alpha$ на главной диагонали равносильно умножению матрицы на число $\alpha$.

**<u>Умножение на диагональную матрицу</u>**

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/3edd69882500c75dbdc40da9b39b49c5/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_13.png)

* При умножении на диагональную матрицу справа каждый столбец матрицы $A$ умножается на соответствующий коэффициент, стоящий на диагонали матрицы $D$.

* При умножении на диагональную матрицу слева каждая строка матрицы $A$ умножается на соответствующий коэффициент, стоящий на диагонали матрицы $D$.

> Умножение на диагональную матрицу не является перестановочным в общем случае.

> Умножение двух диагональных матриц означает перемножение соответствующих элементов, стоящих на главной диагонали. Причём умножение двух диагональных матриц перестановочно.

## <center>Умножение и транспонирование матриц</center>

При транспонировании меняется порядок произведения матриц.

Найти транспонированное произведение матриц ${\left(А \cdot \mathrm{\ }B\right)}^T$ и $B^TA^T$, если:

$A=\left( \begin{array}{cc} 1 & 2 \\ 3 & 1 \end{array} \right)$ и $B=\left( \begin{array}{cc} 2 & 6 \\ 1 & 1 \end{array} \right)$

${\left(A\cdot \ B\right)}^T={\left(\left( \begin{array}{cc} 1 & 2 \\ 3 & 1 \end{array} \right)\cdot \left( \begin{array}{cc} 2 & 6 \\ 1 & 1 \end{array} \right)\right)}^T={\left( \begin{array}{cc} 1\cdot 2+2\cdot 1 & 1\cdot 6+2\cdot 1 \\ 3\cdot 2+1\cdot1 & 3\cdot 6+1\cdot 1 \end{array} \right)}^T={\left( \begin{array}{cc} 4 & 8 \\ 7 & 19 \end{array} \right)}^T=\left( \begin{array}{cc} 4 & 7 \\ 8 & 19 \end{array} \right)$

А теперь найдём $B^TA^T$:

$B^TA^T={\left( \begin{array}{cc} 2 & 6 \\ 1 & 1 \end{array} \right)}^T\cdot {\left( \begin{array}{cc} 1 & 2 \\ 3 & 1 \end{array} \right)}^T=\left( \begin{array}{cc} 2 & 1 \\ 6 & 1 \end{array} \right)\cdot \left( \begin{array}{cc} 1 & 3 \\ 2 & 1 \end{array} \right)=\left( \begin{array}{cc} 2\cdot 1+1\cdot 2 & 2\cdot 3+1\cdot 1 \\ 6\cdot 1+1\cdot 2 & 6\cdot 3+1\cdot 1 \end{array} \right)=\left( \begin{array}{cc} 4 & 7 \\ 8 & 19 \end{array} \right)$

Как и ожидалось, результаты умножения совпали.

**Матрицей Грама** системы векторов называется матрица, составленная из скалярных произведений их исходной матрицы. То есть:

$G=X^T\cdot X$ или $G=X{\cdot X}^T$

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/c6ad51558b9fd49648e1682349202018/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_60_2.png)

Матрица скалярных произведений **строк** матрицы Х или матрица Грама для векторов (1, 1), (1, 2) и (0, -1).

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/4ee8d93b553fcc043082c18a5ff660d4/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_0002.png)

Матрица скалярных произведений **столбцов** матрицы Х или матрица Грама для векторов (1, 1, 0) и (1, 2, -1).

> Обе матрицы Грама симметричны. Забегая вперёд, отметим, что матрица Грама системы векторов всегда имеет вещественные собственные числа и диагонализируется, а если векторы линейно независимы, то ещё и обратима. Этим мы будем пользоваться при построении и апгрейдах модели линейной регрессии. Матрицы $X$ и $X^T$ можно умножать в любом порядке. В обоих случаях получится симметричная квадратная матрица.

*Смотри блокнот "extra_3"*

In [32]:
# Задание 7.1

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [33]:
A@x

array([26, 30])

In [34]:
# Задание 7.2

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [35]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [36]:
# Задание 7.3

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [37]:
A = np.array([x, y, z])
print(A.T@A)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [38]:
# Задание 7.4

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [39]:
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [40]:
# Задание 7.5

P = Price_DF.values
C = Count_DF.values
styl_inc = (P*C)@(np.ones(5)-com)
print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


# <center>Обратная матрица</center>

Из школьного курса алгебры известно, что операция деления числа $b$ на число $a$ — это на самом деле умножение числа $b$ на число, обратное $a$.

Обратным к числу $a$ называется такое число $a^{-1}$, которое в произведении с числом $a$ даёт 1:

$$a^{-1}-\textrm{т}\textrm{а}\textrm{к}\textrm{о}\textrm{е}\ \textrm{ч}\textrm{и}\textrm{с}\textrm{л}\textrm{о},\ \textrm{ч}\textrm{т}\textrm{о}\ aa^{-1}=1\ \textrm{и}\textrm{л}\textrm{и}\ a^{-1}=\frac{1}{a}$$

Например, обратным к числу 2 будет число $2^{-1}=\frac{1}{2}=0.5$.

> Обратные числа есть у всех чисел, кроме нуля.

> Обратное число всегда одно, и неважно, с какой стороны на него умножать. 

Сразу оговоримся, что мы будем рассматривать **только квадратные матрицы**, так как только для них существуют обратные.

Обратной к матрице $A$ порядка $n$ называется такая матрица $A^{-1}$ порядка $n$, которая в произведении с матрицей $A$ даёт единичную матрицу. Формализуем это выражение:

$$A^{-1},-\textrm{т}\textrm{а}\textrm{к}\textrm{а}\textrm{я}\ \textrm{м}\textrm{а}\textrm{т}\textrm{р}\textrm{и}\textrm{ц}\textrm{а},\ \textrm{ч}\textrm{т}\textrm{о}\ A\cdot A^{-1}=E\ ,\ {\mathrm{dim} \left(A^{-1}\right)\ }={\mathrm{dim} \left(A\right)\ }=(n,\ n)$$

1) Произведение матрицы и обратной к ней является перестановочным (коммутативным).

$$A\cdot A^{-1}=A^{-1}\cdot A=E$$

2) Обратная матрица существует не всегда.

Подсчёт обратной матрицы (2,2):
$${\left( \begin{array}{cc} a_{11} & a_{12} \\ a_{21} & a_{22} \end{array} \right)}^{-1}=\frac{1}{a_{11}a_{22}-a_{12}a_{21}}\cdot \left( \begin{array}{cc} a_{22} & -a_{12} \\ -a_{21} & a_{11} \end{array} \right),$$

Для вычисления обратной матрицы размера $(2,2)$ необходимо:

* поменять элементы, находящиеся на главной диагонали, местами;

* элементы, находящиеся на побочной диагонали, умножить на $(-1)$;

* результат разделить на число $\frac{1}{a_{11}a_{22}-a_{12}a_{21}}$.

Обратная матрица в *Python* вычисляется с помощью функции `numpy.linalg.inv()`:

In [41]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [42]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

> Разделить матрицу $B$ на матрицу $A$ означает умножить $B$ на $A^{-1}$.

## <center>Определитель матрицы</center>

**Определитель матрицы** — это специальная числовая характеристика квадратных матриц, которая является своего рода мерой вырожденности матрицы: чем ближе определитель к нулю, тем хуже работают стандартные численные алгоритмы для вычисления обратных матриц.

Обозначение: $\mathrm{det}\mathrm{}(A)$ или $|A|$.

> У определителя также имеется и геометрический смысл. Модуль определителя равен объёму $n$-мерного параллелепипеда, натянутого на столбцы матрицы.

В простейшем случае матрицы 2x2 для расчёта определителя необходимо просто перемножить элементы главной и побочной диагоналей и вычесть второе из первого.

$$\mathrm{det}\mathrm{}(A)=det\left( \begin{array}{cc} a & b \\ c & d \end{array} \right)=ad-bc$$

В *Python* определитель считается с помощью функции `np.linalg.det()`.

In [43]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999996


У определителя есть множество полезных свойств. 

1) Определитель единичной матрицы предсказуемо равен единице:

$${\mathrm{det} \left(E\right)\ }=1$$

2) Для диагональной матрицы определитель равен произведению диагональных элементов:

$${\mathrm{det} \left(diag({\alpha }_1,\ {\alpha }_2,\ \dots ,{\alpha }_n\right))\ }={\alpha }_1\cdot {\alpha }_2\cdot \dots \cdot {\alpha }_n$$

3) При умножении матрицу на константу $\beta \in \mathbb{R}$ определитель увеличивается в $\beta^n$ раз, где $n$ — порядок матрицы:

$${\mathrm{det} \left(\beta A\right)\ }={\beta }^n\mathrm{det}\mathrm{}(A)$$

4) При транспонировании определитель матрицы не изменяется:

$${\mathrm{det} \left(A\right)\ }=\mathrm{det}\mathrm{}(A^T)$$

5) Определитель произведения матриц $A$ и $B$ равен произведению определителей этих матриц и не зависит от порядка умножения:

$${\mathrm{det} \left(A\cdot B\right)=det\left(B\cdot A\right)=det\left(A\right)\cdot \ }det\left(B\right)$$

6) Из последнего свойства определителя получается связь определителей матрицы и соответствующей ей обратной матрицы: их произведение равно единице:

$${\mathrm{det} \left(A\right)\ }{\mathrm{det} \left(A^{-1}\right)=1\ }$$

## <center>Вырожденность матрицы</center>

Матрица $A$ называется вырожденной, если её определитель равен 0:

$${\mathrm{A-}\textrm{в}\textrm{ы}\textrm{р}\textrm{о}\textrm{ж}\textrm{д}\textrm{е}\textrm{н}\textrm{н}\textrm{а}\textrm{я},\ \textrm{е}\textrm{с}\textrm{л}\textrm{и}\ \mathrm{det} \left(A\right)\ }=0$$

Для вырожденных матриц **не существует обратных матриц**, так как в противном случае пришлось бы делить на 0 при подсчёте. Строки и столбцы такой матрицы являются линейно зависимыми и выражаются друг через друга. 

Однако полностью вырожденные матрицы существуют только в теории. На практике мы сталкиваемся с матрицами, близкими к вырожденным. Определитель таких матриц не равен 0, но близок к нему (например, равен $10^{-5}$):

$${\mathrm{det} \left(A\right)\ }\to 0$$

# <center>СЛАУ</center>

# <center>Система линейных алгебраических уравнений</center>

Пример **неоднородной СЛАУ** — системы, у которой хотя бы один коэффициент справа отличен от 0:

$$\left\{ \begin{array}{c} 2x+3y=1540 \\ 2y-x=210 \end{array} \right.$$


Если все коэффициенты справа равны 0, то система называется **однородной СЛАУ**:

$$\left\{ \begin{array}{c} 2x+3y=0 \\ 2y-x=0 \end{array} \right.$$


> Системы со множеством возможных решений называются неопределёнными и представляют особый интерес в линейной алгебре.

Совокупность уравнений первой степени, в которых каждая переменная и коэффициенты в ней являются вещественными числами, называется **системой линейных алгебраических уравнений (СЛАУ)** и в общем случае записывается как:

$$\left\{ \begin{array}{c} a_{11}x_1+a_{12}x_2+\dots +a_{1m}x_m=b_1 \\ a_{21}x_1+a_{22}x_2+\dots +a_{2m}x_m=b_2 \\ \dots \\ a_{n1}x_1+a_{n2}x_2+\dots +a_{nm}x_m=b_n \end{array} \right.\ (1),$$

где

* $n$ — количество уравнений;
* $m$ — количество переменных;
* $x_i$ — неизвестные переменные системы;
* $a_{ij}$ — коэффициенты системы;
* $b_i$ — свободные члены системы.

СЛАУ (1) называется **однородной**, если все свободные члены системы равны 0 $b_1=b_2=⋯=b_n=0$:

$$\textrm{С}\textrm{Л}\textrm{А}\textrm{У}-\textrm{о}\textrm{д}\textrm{н}\textrm{о}\textrm{р}\textrm{о}\textrm{д}\textrm{н}\textrm{а}\textrm{я},\ \textrm{е}\textrm{с}\textrm{л}\textrm{и}\ \forall b_i=0$$

СЛАУ (1) называется **неоднородной**, если хотя бы один из свободных членов системы отличен от 0:

$$\textrm{С}\textrm{Л}\textrm{А}\textrm{У}- \textrm{н}\textrm{е}\textrm{о}\textrm{д}\textrm{н}\textrm{о}\textrm{р}\textrm{о}\textrm{д}\textrm{н}\textrm{а}\textrm{я},\ \textrm{е}\textrm{с}\textrm{л}\textrm{и}\ \exists b_i\neq 0$$

Решением СЛАУ (1) называется такой набор значений неизвестных переменных $x_1,x_2,…,x_n$ при котором каждое уравнение системы превращается в равенство.

СЛАУ (1) называется **определённой**, если она имеет только одно решение, и **неопределённой**, если возможно больше одного решения.

Любая **однородная** СЛАУ может иметь **только два случая решения**:

* Только одно тривиальное решение — все независимые переменные равны 0: $\forall x_i=0$. Данное решение существует всегда.

* Бесконечное множество решений.

## <center>Матричная запись СЛАУ</center>

Любую СЛАУ можно представить в матричном виде: $A\overrightarrow{x}=\overrightarrow{b}$. Данная запись системы называется **матричным уравнением**.

Если СЛАУ однородная, то принято записывать вектор $\overrightarrow{b}$ как нулевой вектор $\overrightarrow{0}$: $A\overrightarrow{x}=\overrightarrow{0}$.

Введём матрицу системы $A$. Она будет квадратной (2х2) и будет состоять из двух векторов-столбцов: ${\left(a_{11},\ a_{21}\right)}^T={\left(2,\ 2\right)}^T$ и ${{\left(a_{12},\ a_{22}\right)}^T=\left(-1,\ 2\right)}^T$:

$$A=\left( \begin{array}{cc} 2 & 3 \\ -1 & 2 \end{array} \right)$$

Введём вектор неизвестных коэффициентов $\overrightarrow{x}={{\left(x_1,\ x_2\right)}^T=\left(x,\ y\right)}^T$ и вектор свободных членов $\overrightarrow{b}={\left(b_1,\ b_2\right)}^T=(1540,\ 210)$.

Теперь у нас есть все компоненты, чтобы составить матричное уравнение:

$$A\overrightarrow{x}=\overrightarrow{b}$$

$$\left( \begin{array}{cc} 2 & 3 \\ -1 & 2 \end{array} \right)\left( \begin{array}{c} x \\ y \end{array} \right)=\left( \begin{array}{c} 1540 \\ 210 \end{array} \right)$$

## <center>Линейная зависимость системы векторов</center>

Набор векторов называется **линейно зависимым**, если нам удалось создать нетривиальную нулевую линейную комбинацию, т. е. взять такую взвешенную сумму векторов $\overrightarrow{v_1},\overrightarrow{v_2},\dots ,\overrightarrow{v_m}$ с коэффициентами ${\omega }_1{,\omega }_2,\dots ,{\omega }_m$, что в итоге получился нулевой вектор и при этом не все коэффициенты $\omega$ равны нулю:

То есть $\overrightarrow{v_1},\overrightarrow{v_2},\dots ,\overrightarrow{v_m}$ линейно зависимы, если $\exists \  {\omega }_1{,\omega }_2,\dots ,{\omega }_m$:

$${\omega }_1\overrightarrow{v_1}+{\omega }_2\overrightarrow{v_2}+\dots +{\omega }_m\overrightarrow{v_m}=\overrightarrow{0}$$

Обобщим наш метод определения линейной (не)зависимости с помощью СЛАУ в виде **алгоритма**:

1) Для начала необходимо составить условие линейной зависимости векторов:

$${\omega }_1\overrightarrow{v_1}+{\omega }_2\overrightarrow{v_2}+\dots +{\omega }_m\overrightarrow{v_m}=\overrightarrow{0}$$

Затем нужно преобразовать полученную однородную СЛАУ к матричному виду, $A\overrightarrow{\omega }=\overrightarrow{0}$, привести матрицу $A$ к ступенчатому виду и решить исходную СЛАУ.

2) Если у системы есть ненулевое решение, то есть хотя бы один из коэффициентов ${\omega }_i\neq 0$, то векторы являются линейно зависимыми.

3) В противном случае векторы линейно независимы.

> На самом деле для определения линейной зависимости векторов нам будет достаточно знать, существует ли вообще ненулевое решение, а сами коэффициенты $\omega_i$ нас не интересуют. В этом нам поможет такая характеристика матрицы, как **ранг**.

## <center>Ранг матрицы</center>

$$\left( \begin{array}{ccc} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{array} \right)\textrm{и}\left( \begin{array}{ccc} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{array} \right)$$

В первом случае у нас есть две нулевые строки. Таким образом, во всей матрице независимых столбцов будет два — это те столбцы, которые стоят в ступеньках. Отсюда следует, что все три столбца (векторы $\overrightarrow{v_1}$, $\overrightarrow{v_2}$ и $\overrightarrow{v_3}$) являются линейно зависимыми между собой.

Во втором случае все три столбца являются линейно независимыми, так как у матрицы три ступени.

**Ранг матрицы** — это количество линейно независимых столбцов. Обозначение: $rk$ или $rank$.

**Ранг системы векторов** — это размерность этой системы.

* Если ранг равен количеству векторов в системе ($rk(A)=n$), то система векторов является линейно независимой.

* Если ранг меньше, чем количество векторов в системе ($rk(A)<n$), можно смело говорить, что система векторов является линейно зависимой. В линейно независимой системе нельзя выразить один из векторов через остальные, в зависимой — можно, однако не любой. 

Знание ранга даёт нам только количество линейно независимых векторов, но не говорит, какие именно векторы выражаются или не выражаются друг через друга. Для ответа на этот вопрос необходимо найти **базис системы**.

**Базис** — это такая часть системы векторов $\overrightarrow{v_1},\ \overrightarrow{v_2},\ \dots ,\ \overrightarrow{v_k}$, через которую можно выразить все остальные векторы $k \le n$. 

**Базис** — это максимальная линейно независимая подсистема векторов $\overrightarrow{v_1}, \ \overrightarrow{v_2}, \ \dots, \ \overrightarrow{v_n}$.

> Количество векторов в базисе совпадает с рангом системы. При этом самих базисов может быть несколько, мы выбираем их произвольно.

Рассмотрим пример того, как вычислить ранг в *Python*. Для этого в библиотеке numpy существует специальная функция `linalg.matrix_rank()`:

In [44]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


Мы видим, что ранг системы равен 2, а векторов три — значит система является линейно зависимой. В качестве базиса можем взять любые два вектора. Очевидно, каждая пара здесь является линейно независимой, т. к. никакие два вектора не пропорциональны.

In [45]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

3


В данном примере ранг равен 3 — значит векторы линейно независимы и в базис войдут все три вектора.

## <center>Свойства ранга матрицы</center>

Начнём с **прямоугольных** матриц. Пусть задана прямоугольная матрица $A$ размерностью $dim(A)=(n,m)$.

* Ранг матрицы не может быть больше, чем количество её строк или столбцов:

$$rk\left(A\right)\le \mathrm{min}\mathrm{}(n,\ m)$$

* Если ранг равен одному из этих показателей, то такая матрица называется **матрицей максимального (или полного) ранга**.

$$rk\left(A\right)=\mathrm{min}\mathrm{}(n,\ m)$$

Теперь поговорим о **квадратных** матрицах. 

Пусть задана прямоугольная матрица $A$ размерностью $dim(A)=(n,n)$.

В квадратных матрицах ранг связан с обратимостью и вырожденностью. Ранее мы выяснили, что квадратная матрица порядка $n$ обратима, то есть для неё существует $A^{-1}$ тогда и только тогда, когда её определитель не равен нулю: $det(A) \neq 0$.

Равносильными условиями являются линейная независимость столбцов (или строк), а также максимальный ранг. То есть для матрицы $A$ существует обратная матрица $A^{-1}$, если:

* Все столбцы/строки $A$ линейно независимы.

* Ранг матрицы равен её порядку: $rk(A)=n$.

Любая квадратная матрица не максимального ранга вырождена (у неё нет обратной $A^{-1}$), и чем меньше ранг, тем меньше линейно независимых столбцов и строк в матрице:

$$rk\left(A\right)<n$$

> В регрессиях это может означать, что чем меньше ранг матрицы значений факторов, тем больше в ней мусора: факторов, которые выражаются через другие и не несут в себе никакой дополнительной информации. Это и называется **мультиколлинеарностью**.

*Смотри блокнот "extra_4"*

In [46]:
# Задание 10.1

A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [48]:
A_inv = np.linalg.inv(A)
print(round(A_inv[1,0], 3))

0.375


In [49]:
# Задание 10.2

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [50]:
A = np.array([v1,v2,v3,v4]).T
np.linalg.matrix_rank(A)

4

In [51]:
# Задание 10.4

G = A.T @ A
print(G[0,3])

-35


In [52]:
# Задание 10.5

det = np.linalg.det(G)
print(round(det))

3716648


In [53]:
# Задание 10.7

G_inv = np.linalg.inv(G)
print(round(G_inv[2,0], 3))

-0.026
