## <center>Основы математического языка: кванторы</center>

Познакомимся с **кванторами** и символами, позволяющими записывать математические формулировки:

* Символ $\forall$ читается как «для любого» и называется **квантором всеобщности**. Он заменяет собой слова «любой», «всякий», «для любого» и т. п.

* Символ $\exists$ читается как «существует» и называется **квантором существования**, а $\exists !$ читается как «существует единственный» и называется **квантором существования и единственности**.   заменяет слова «существует», «найдётся» и т. п.

* Знак импликации $\rightarrow$ (или $\Rightarrow$) воспринимается как замена слов «следует», «влечёт», «вытекает», «имеет место», «выполняется».

* Знак равносильности или эквивалентности $\leftrightarrow$ (или $\Leftrightarrow$) заменяет словосочетания «тогда и только тогда, когда», «в том и только том случае, когда», «если и только если».

* Двоеточие $:$ в математических формулах читается как «такой, что».

* Вертикальная черта $|$ означает «при условии, что».

# <center>Основные понятия линейной алгебры: векторы</center>

Наиболее общее определение, которое подойдёт ко всем случаям: **Вектор** — это набор чисел, записанных в определённом порядке (в столбец или в строку).

$$\overrightarrow{s}=(s_1, s_2, ..., s_m)$$

$$\overrightarrow{s}=\left( \begin{array}{c} s_1 \\ s_2 \\ \dots \\ s_m \end{array} \right)$$

Числа $s_1, s_2, ..., s_m$ называются **координатами вектора**, а количество этих координат ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=m$ называется **размерностью вектора**.

In [1]:
import numpy as np

In [2]:
# Задаём вектор как одномерный массив numpy с помощью функции np.array
s = np.array([33, 64, 50, 45])
s

array([33, 64, 50, 45])

In [3]:
# Находим третью координату
s[2]

50

In [4]:
# Находим размерность вектора
len(s)

4

Длина трёхмерного вектора $\overrightarrow{s}$ определяется аналогично двухмерному:

$$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+{\left(s_3\right)}^2}$$

> В общем случае вектор $\overrightarrow{\boldsymbol{s}}\boldsymbol{=(}{\boldsymbol{s}}_{\boldsymbol{1}}\boldsymbol{,\ }{\boldsymbol{s}}_{\boldsymbol{2}}\boldsymbol{,\ \dots ,\ }{\boldsymbol{s}}_{\boldsymbol{m}}\boldsymbol{)}$ размерностью ${\boldsymbol{dim} \left(\overrightarrow{\boldsymbol{s}}\right)\ }\boldsymbol{=}\boldsymbol{m}$ задаёт в векторном $m$-мерном пространстве $\boldsymbol{S}\boldsymbol{\subset }{\mathbb{R}}^{\boldsymbol{m}}$ направленный отрезок с началом в точке $O=(0,0,…,0)$ и концом в точке $(s_1,s_2,…,s_m)$. 

Длина такого вектора $\overrightarrow{s}$ будет вычисляться так:

$$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+\dots +{\left(s_m\right)}^2}=\sqrt{\sum^m_{j=1}{{\left(s_j\right)}^2}}$$

## <center>Базовые операции с векторами</center>

Сложение и вычитание векторов в *Python* происходит при помощи знаков + и -. Причём важно задать векторы именно как массивы *numpy*, а не как обычные списки типа *list*.

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [6]:
a + b

array([15, 23, 14,  8])

In [7]:
a - b

array([ 5, -7, -4, -6])

Пусть задан вектор ${\overrightarrow{v}}_1$ из векторного пространства $V\subset {\mathbb{R}}^m$:

$$\overrightarrow{v_1}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)$$

Тогда результатом умножения векторов ${\overrightarrow{v}}_1$ на число $\omega \in \mathbb{R}$ называется новый вектор ${\overrightarrow{v}}_2$, принадлежащий тому же векторному пространству $V$, с координатами:

$$\overrightarrow{v_2}=\omega \overrightarrow{v_1}=\omega \left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)=\left( \begin{array}{c} \omega v_{11} \\ \omega v_{12} \\ \dots \\ \omega v_{1m} \end{array} \right)$$

> Векторы ${\overrightarrow{v}}_1$ и ${\overrightarrow{v}}_2$ пропорциональны друг другу с коэффициентом $\omega$. По-другому такие векторы называются коллинеарными. Обозначается: ${\overrightarrow{v}}_1||\overrightarrow{v_2}$.

Если коэффициент пропорциональности положительный ($\omega >0$), векторы сонаправлены (смотрят в одном направлении), если отрицательный ($\omega <0$) — противоположно направлены. Геометрически это значит, что векторы лежат на одной прямой (или параллельных прямых) и направлены в одну или противоположные стороны.

В *Python* число умножается на массив numpy обычным оператором умножения.

In [8]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

> **Примечание о разнице векторов**. В строгой линейной алгебре нет такой отдельной операции, как разница векторов. Под разницей двух векторов $\overrightarrow{v_2}$ и $\overrightarrow{v_1}$ понимается сложение векторов $\overrightarrow{v_2}$ и $(-1)\overrightarrow{v_1}$.

> Геометрически умножить вектор на скаляр означает изменить его длину в $\alpha$ раз. Если $|\alpha |>1$, то длина вектора пропорционально увеличивается. Если $|\alpha |<1$, то длина вектора уменьшается. Если $\alpha$ — положительное число ($\alpha>0$), то вектор сохраняет своё направление. Если $\alpha$ — отрицательное число ($\alpha<0$), то вектор меняет своё направление на противоположное.

## <center>Линейная комбинация векторов</center>

**Линейная комбинация** — это объединение операций сложения векторов и умножения на скаляр в одну. Каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются.

В *Python* линейная комбинация полностью соответствует своему названию и вычисляется как комбинация сложения векторов и умножения вектора на число.

In [9]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

Самое интересное в линейных комбинациях — это особые случаи, а именно **нулевая линейная комбинация**. Линейная комбинация векторов называется нулевой, если результат линейной комбинации равен нулевому вектору.

Как получить нулевой вектор из линейной комбинации? Самый простой вариант — чтобы все коэффициенты линейной комбинации были равны 0. Однако такой случай, называемый **тривиальным**, нам не интересен.

Нулевая линейная комбинация называется **нетривиальной**, если хотя бы один из коэффициентов отличен от 0.

Предположим, что нам удалось составить нетривиальную комбинацию, то есть удалось подобрать такие ${\omega }_i\neq 0$, что вектор $\overrightarrow{u}=\overrightarrow{0}$.

В таком случае векторы, из которых была составлена линейная комбинация $\overrightarrow{v_1},\ \overrightarrow{v_2},\ \dots ,\ \overrightarrow{v_n}$, называются **линейно зависимыми**.

Тогда хотя бы один из векторов, но не обязательно любой, в линейной комбинации можно выразить через другие векторы, представив его как линейную комбинацию.

Или же, возможно, как мы ни старались, но нам не удалось подобрать такие коэффициенты ${\omega }_i\neq 0$, чтобы составить нулевую нетривиальную линейную комбинацию. Такие векторы называются **линейно независимыми**. В таком случае ни один из векторов не выражается через другие векторы.

## <center>Скалярное произведение векторов</center>

Существует четыре способа умножить векторы между собой:

* Скалярное произведение. Результат — число. 
* Векторное произведение. Результат — вектор.
* Смешанное произведение. Результат — число. 
* Тензорное произведение. Результат — матрица.

Мы рассмотрим скалярное произведение.

Чтобы найти **скалярное произведение двух векторов**, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится.  

В *Python* скалярное произведение векторов вычисляется при помощи функции `np.dot()`:

In [10]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

Через скалярное произведение можно выразить длину вектора (обозначается как $\left|\overrightarrow{v}\right|$ или $|\left|\overrightarrow{v}\right||$).

В линейной алгебре **длина вектора** определяется как квадратный корень из скалярного произведения вектора с самим собой.

Длина вектора всегда неотрицательна и показывает, как близок вектор к нулевому.

Скалярное произведение — это не просто удобная форма записи умножения векторов. На самом деле скалярное произведение обладает рядом очень полезных **свойств**.

1) Линейность.

2) Скалярное произведение двух векторов $\overrightarrow{v_1}$ и $\overrightarrow{v_2}$ в точности равно произведению длин этих векторов $\left|\overrightarrow{v_1}\mathrm{\ }\right|$ и $\left|\overrightarrow{v_2}\mathrm{\ }\right|$ на косинус угла между ними $\mathrm{cos}\mathrm{}(\overrightarrow{v_1},\ \overrightarrow{v_2})$.

3) Из последнего свойства следует ещё одно свойство скалярного произведения. Если скалярное произведение двух векторов равно 0, то вектора ортогональны (находятся под углом 90°). И наоборот: если вектора ортогональны друг другу, их скалярное произведение равно 0.

## <center>Векторная запись линейной регрессии</center>

$$\hat{y}={\omega }_0+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$$

Давайте добавим коэффициент 1 перед параметром $\omega_0$:

$$\hat{y}={\omega }_01+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$$

А теперь представим параметры модели в виде вектора $\overrightarrow{\omega }$ и признаки — в виде вектора $\overrightarrow{x}$:

$$\overrightarrow{\omega }=\left( \begin{array}{c} {\omega }_0 \\ {\omega }_1 \\ {\omega }_2 \\ \dots \\ {\omega }_m \end{array} \right)\ \textrm{и}\ \overrightarrow{x}=\left( \begin{array}{c} 1 \\ x_1 \\ x_2 \\ \dots \\ x_m \end{array} \right)$$

Тогда уравнение линейной регрессии можно записать в лаконичной векторной форме скалярного произведения двух векторов $\overrightarrow{\omega }$ и $\overrightarrow{x}$:

$$\hat{y}=\overrightarrow{\omega }\cdot \overrightarrow{x}$$

Возник вопрос: как ищутся коэффициенты линейной комбинации ${\omega }_1$ и ${\omega }_2$? Не искать же их полным перебором.

На этот вопрос в своё время ответил Гаусс и создал знакомый нам **метод наименьших квадратов (МНК)**, который мы уже многократно использовали в модулях по машинному обучению. Но, чтобы познакомиться с МНК поближе с математической точки зрения, нам с вами необходимо изучить тему матриц и матричных преобразований.

В блокноте *"extra"* мы рассматриваем пример нормирования вектора. Интуитивно нормирование можно объяснить так ↓

**Нормирование вектора** — это получение вектора с тем же направлением, что и исходный, но с нормой 1.

Норма вектора вычисляется как корень из суммы квадратов его компонент. Её физический смысл: норма показывает, насколько вектор «большой».

**Длина вектора** (в физическом смысле) — это то же, что и норма, применимо к векторам в реальном пространстве.

> Нормирование производится делением вектора на его норму.

In [11]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [12]:
# Задание 3.3

Hut_Paradise_values = Hut_Paradise_DF.values

In [13]:
print('vektor for apartment 5:', Hut_Paradise_values[4])

vektor for apartment 5: [40 33  1  6 20 16]


In [14]:
# Задание 3.4

print('vektor for floors:', Hut_Paradise_values[:,3])

vektor for floors: [ 5 12 10  3  6 13  8 21  5]


In [15]:
# Задание 3.5

unliv_area = Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]
print('vektor for unliv.area:', unliv_area)

vektor for unliv.area: [13 12 15 13 17  9 20 15 25]


In [16]:
# Задание 3.6

time = np.array([10,20,30,15,5,40,20,8,20])
print(Hut_Paradise_values[:,4] @ time)

1348


In [17]:
# Задание 3.7

u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [18]:
c=2*v-3*w
print(c)

[-3 14  3  4  2]


# <center>Матрицы</center>

**Матрица** — это структура, представляющая собой таблицу, состоящую из чисел, расположенных по строкам и столбцам.

> Математики не любят громоздкую запись, поэтому, чтобы обозначить, что матрица состоит из чисел $a_{ij}$, нередко пишут следующим образом: $A=\left(a_{ij}\right),\ \ a_{ij}\in \mathbb{R}\mathrm{,}\mathrm{\ }i=1,\ 2,\dots ,n \textit{ } j=1,\ 2,\dots ,m$.

> **Элементами главной диагонали** называются элементы, у которых индексы строк и столбцов совпадают, то есть $a_{ij}, \  i=j$.

Матрицу можно создать функцией `np.matrix()` или `np.array()`. Разницу между двумя этими способами мы обсудим в скринкасте.

За размер матрицы отвечает атрибут `shape`. 

Матрицы, как и массивы, индексируются с 0, а не с 1.

In [19]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [21]:
A.shape

(4, 3)

In [20]:
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])

a_23= 1 a_32= 3 a_33= 1


## <center>Классификация матриц</center>

Матрицы различаются по форме и по содержанию.

* **Прямоугольные матрицы** — это матрицы, у которых количество строк $n$ не совпадает с количеством столбцов $m$, т. е. $n\neq m$.
    * высокие
    * длинные

* **Квадратные матрицы** — это матрицы, у которых количество строк $n$ совпадает с количеством столбцов $m$, т. е. $n= m$. **Порядком** квадратной матрицы называется количество строк (и столбцов соответственно) в ней.

* **Вектор-столбец** — это матрица размера $(n,1)$.

* **Вектор-строка** — это матрица размера $(1,m)$.

* **Нулевая матрица** — это матрица, у которой все элементы являются нулём. Формально это записывается как $A=\left(a_{ij}\right),\ {\forall a}_{ij}=0$.

* **Матрица-единица**, или **матрица единиц** — это матрица, у которой все элементы являются единицей. Формальная запись: $A=\left(a_{ij}\right),\ {\forall a}_{ij}=1$.

> Виды матриц, о которых пойдёт речь далее, бывают только квадратными.

* **Треугольная матрица** — это квадратная матрица, у которой элементы выше или ниже главной диагонали равны 0.

    * Нижнетреугольная матрица: $A=\left(a_{i j}\right)=\left\{\begin{array}{l} a_{i j} \neq 0, \text { при } i \geq j \\ a_{i j}=0, \text { при } i<j \end{array}\right.$

    * Верхнетреугольная матрица: $A=\left(a_{i j}\right)=\left\{\begin{array}{l} a_{i j}=0, \text { при } i \geq j \\ a_{i j} \neq 0, \text { при } i<j \end{array}\right.$

* **Симметричная матрица** — это квадратная матрица, у которой элементы равны друг другу относительно главной диагонали. Формально записывается как: $S=\left(s_{ij}\right),{\ s}_{ij}={\ s}_{ji}\ \forall i,\ j$.

> Симметричные матрицы — это очень важный вид матриц. Например, матрица корреляций, с которой мы с вами уже множество раз сталкивались, является симметричной: по её диагонали находятся единицы — корреляции признаков с самими собой, а в остальных ячейках — коэффициенты корреляции.

* **Диагональная матрица** — это симметричная матрица, у которой вне главной диагонали стоят нули. Формально записывается как: 

$$S=\left(s_{ij}\right)=\left\{ \begin{array}{c} s_{ij}={\ s}_{ji}=0,\ \textrm{п}\textrm{р}\textrm{и}\ i\neq j \\ s_{ij}\neq 0,\ \textrm{п}\textrm{р}\textrm{и}\ i=j \end{array} \right.$$

У диагональной матрицы есть ещё одно обозначение: $S=diag({\alpha }_1,\ {\alpha }_2,\ \dots ,\ {\alpha }_n),$ где $\alpha_i$ — элементы, стоящие на главной диагонали.

* **Скалярная, или шаровая матрица** — это диагональная матрица, у которой по диагонали стоит одно и тоже число.

$$S=\left(s_{ij}\right)=\left\{ \begin{array}{c} s_{ij}=0,\ \textrm{п}\textrm{р}\textrm{и}\ i\neq j \\ s_{ij}=\alpha ,\ \textrm{п}\textrm{р}\textrm{и}\ i=j \end{array} \right.$$

Альтернативная запись: $S=diag(\alpha )$.

* **Единичная** (не путать с матрицей единиц!) **матрица** — это скалярная матрица, у которой $\alpha=1$. Единичная матрица является настолько важной в линейной алгебре, что даже имеет собственное специальное обозначение — латинская буква $E$.

$$E=\left(e_{ij}\right)=\left\{ \begin{array}{c} e_{ij}=0,\ \textrm{п}\textrm{р}\textrm{и}\ i\neq j \\ e_{ij}=1,\ \textrm{п}\textrm{р}\textrm{и}\ i=j \end{array} \right.$$

## <center>Базовые действия над матрицами</center>

К базовым относятся следующие операции:

* Сложение матриц. Результат — матрица.
* Умножение матрицы на число. Результат —  матрица.
* Транспонирование. Результат —  матрица.

**Операция транспонирования** — это матричная операция, при которой строки и столбцы меняются местами. Двойное транспонирование матрицы возвращает её к первичному виду. 

> Симметричные матрицы инварианты к операции транспонирования, то есть не изменяются.

> Матрица $A$ называется симметричной, если она не меняется при транспонировании, т. е. $A=A^T$.

*Смотри ноутбук "extra_2"*

In [22]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [23]:
# Задание 5.1

Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
print(Inc[0,0], Inc[1,1], Inc[2,2])

100 200 100


In [24]:
# Задание 5.2

Cons=np.array([Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption]).T
print(Cons[0,0], Cons[1,1], Cons[2,2])

50 80 140


In [27]:
# Задание 5.3

New_Inc=Inc*0.87
New_Inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [28]:
# Задание 5.4

P=New_Inc-Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

## <center>Продвинутые операции с матрицами</center>

**<u>Произведение двух матриц</u>**

Пусть заданы две матрицы $A=(a_{ij})$ и $B=(b_{ij})$, причём их размерности: ${\mathrm{dim} \left(A\right)\ }=\left(n,\ m\right)$ и ${\mathrm{dim} \left(B\right)\ }=\left(m,\ l\right)$. Произведением матриц $A$ и $B$ называется матрица $C=(c_{ij})$ размером ${\mathrm{dim} \left(C\right)\ }=\left(n,\ l\right)$ (обратите внимание на размерность), элемент которой, находящийся на пересечении $i$-й строки и $j$-го столбца, равен сумме произведений элементов $i$-й строки матрицы $A$ на соответствующие (по порядку) элементы $j$-го столбца матрицы $B$.

> Умножить матрицу $A$ на матрицу $B$ можно только в том случае, если количество столбцов в матрице $A$ совпадает с количеством строк в матрице $B$.

> Матричное умножение не перестановочно (не коммутативно). То есть перемена мест сомножителей может привести к различным результатам и даже размерностям.

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/a3a6c30c0321475ea48b8488901278cb/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_1.png)

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/163cf195ac716a3f449273547ac0081d/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_2.png)

В *Python* матрицы можно умножить с помощью функции `np.dot()`. При перемене мест сомножителей результат также меняется.

In [29]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [30]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [31]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [32]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [33]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

Произведение квадратных матриц существует, когда порядок обеих матриц совпадает. Причём результатом умножения квадратных матриц будет квадратная матрица того же порядка, что и исходные.

Например, матрицу 3х3 можно умножить только на матрицу 3х3, но нельзя на матрицу 3х4 или 4х3 или, тем более, 11х23.

**<u>Произведение матрицы и вектора</u>**

Так как вектор — это частный случай матрицы размерностью $(1,m)$ или $(n,1)$, то такое умножение полностью подчиняется правилам, которые мы ввели ранее. По определению произведения матриц результатом умножения матрицы на вектор всегда получается вектор той же размерности, что и исходный.

> Вектор-столбец умножается на матрицу справа, а вектор-строка — слева.

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/2b37a2cf3d333dc0a60dfba2f15fd31c/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_5.png)

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/c75fa4bc4a25adf76fdca272a088fcbc/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_6.png)

**<u>Тензорное произведение векторов</u>**

**Тензорное произведение** — это результат матричного умножения вектора-столбца на вектор-строку. Результатом тензорного произведения является матрица.

Размерности векторов, участвующих в умножении, составляют ${\mathrm{dim} \left(\overrightarrow{v}\right)\ }=(3,1)$ и ${\mathrm{dim} \left({\overrightarrow{u}}^T\right)\ }=(1,3)$. В результате у нас должна получиться матрица 3x3.

![image.png](https://lms-cdn.skillfactory.ru/assets/courseware/v1/6af692dc1c836c797a52843d4bfdcb35/asset-v1:SkillFactory+MIPTDS+SEPT22+type@asset+block/MATHML_md1_6_7.png)

У тензорного произведения есть специальное обозначение — $\otimes$:

$$\overrightarrow{v}\otimes \overrightarrow{u}=\left( \begin{array}{ccc} 4 & 5 & 6 \\ 8 & 10 & 12 \\ 12 & 15 & 18 \end{array} \right)$$

> В случае скалярного произведения векторов всегда получается число, а в случае тензорного — матрица.