## <center>Основы математического языка: кванторы</center>

Познакомимся с **кванторами** и символами, позволяющими записывать математические формулировки:

* Символ $\forall$ читается как «для любого» и называется **квантором всеобщности**. Он заменяет собой слова «любой», «всякий», «для любого» и т. п.

* Символ $\exists$ читается как «существует» и называется **квантором существования**, а $\exists !$ читается как «существует единственный» и называется **квантором существования и единственности**.   заменяет слова «существует», «найдётся» и т. п.

* Знак импликации $\rightarrow$ (или $\Rightarrow$) воспринимается как замена слов «следует», «влечёт», «вытекает», «имеет место», «выполняется».

* Знак равносильности или эквивалентности $\leftrightarrow$ (или $\Leftrightarrow$) заменяет словосочетания «тогда и только тогда, когда», «в том и только том случае, когда», «если и только если».

* Двоеточие $:$ в математических формулах читается как «такой, что».

* Вертикальная черта $|$ означает «при условии, что».

# <center>Основные понятия линейной алгебры: векторы</center>

Наиболее общее определение, которое подойдёт ко всем случаям: **Вектор** — это набор чисел, записанных в определённом порядке (в столбец или в строку).

$$\overrightarrow{s}=(s_1, s_2, ..., s_m)$$

$$\overrightarrow{s}=\left( \begin{array}{c} s_1 \\ s_2 \\ \dots \\ s_m \end{array} \right)$$

Числа $s_1, s_2, ..., s_m$ называются **координатами вектора**, а количество этих координат ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=m$ называется **размерностью вектора**.

In [1]:
import numpy as np

In [2]:
# Задаём вектор как одномерный массив numpy с помощью функции np.array
s = np.array([33, 64, 50, 45])
s

array([33, 64, 50, 45])

In [3]:
# Находим третью координату
s[2]

50

In [4]:
# Находим размерность вектора
len(s)

4

Длина трёхмерного вектора $\overrightarrow{s}$ определяется аналогично двухмерному:

$$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+{\left(s_3\right)}^2}$$

> В общем случае вектор $\overrightarrow{\boldsymbol{s}}\boldsymbol{=(}{\boldsymbol{s}}_{\boldsymbol{1}}\boldsymbol{,\ }{\boldsymbol{s}}_{\boldsymbol{2}}\boldsymbol{,\ \dots ,\ }{\boldsymbol{s}}_{\boldsymbol{m}}\boldsymbol{)}$ размерностью ${\boldsymbol{dim} \left(\overrightarrow{\boldsymbol{s}}\right)\ }\boldsymbol{=}\boldsymbol{m}$ задаёт в векторном $m$-мерном пространстве $\boldsymbol{S}\boldsymbol{\subset }{\mathbb{R}}^{\boldsymbol{m}}$ направленный отрезок с началом в точке $O=(0,0,…,0)$ и концом в точке $(s_1,s_2,…,s_m)$. 

Длина такого вектора $\overrightarrow{s}$ будет вычисляться так:

$$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+\dots +{\left(s_m\right)}^2}=\sqrt{\sum^m_{j=1}{{\left(s_j\right)}^2}}$$

## <center>Базовые операции с векторами</center>

Сложение и вычитание векторов в *Python* происходит при помощи знаков + и -. Причём важно задать векторы именно как массивы *numpy*, а не как обычные списки типа *list*.

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [6]:
a + b

array([15, 23, 14,  8])

In [7]:
a - b

array([ 5, -7, -4, -6])

Пусть задан вектор ${\overrightarrow{v}}_1$ из векторного пространства $V\subset {\mathbb{R}}^m$:

$$\overrightarrow{v_1}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)$$

Тогда результатом умножения векторов ${\overrightarrow{v}}_1$ на число $\omega \in \mathbb{R}$ называется новый вектор ${\overrightarrow{v}}_2$, принадлежащий тому же векторному пространству $V$, с координатами:

$$\overrightarrow{v_2}=\omega \overrightarrow{v_1}=\omega \left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)=\left( \begin{array}{c} \omega v_{11} \\ \omega v_{12} \\ \dots \\ \omega v_{1m} \end{array} \right)$$

> Векторы ${\overrightarrow{v}}_1$ и ${\overrightarrow{v}}_2$ пропорциональны друг другу с коэффициентом $\omega$. По-другому такие векторы называются коллинеарными. Обозначается: ${\overrightarrow{v}}_1||\overrightarrow{v_2}$.

Если коэффициент пропорциональности положительный ($\omega >0$), векторы сонаправлены (смотрят в одном направлении), если отрицательный ($\omega <0$) — противоположно направлены. Геометрически это значит, что векторы лежат на одной прямой (или параллельных прямых) и направлены в одну или противоположные стороны.

В *Python* число умножается на массив numpy обычным оператором умножения.

In [8]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

> **Примечание о разнице векторов**. В строгой линейной алгебре нет такой отдельной операции, как разница векторов. Под разницей двух векторов $\overrightarrow{v_2}$ и $\overrightarrow{v_1}$ понимается сложение векторов $\overrightarrow{v_2}$ и $(-1)\overrightarrow{v_1}$.

> Геометрически умножить вектор на скаляр означает изменить его длину в $\alpha$ раз. Если $|\alpha |>1$, то длина вектора пропорционально увеличивается. Если $|\alpha |<1$, то длина вектора уменьшается. Если $\alpha$ — положительное число ($\alpha>0$), то вектор сохраняет своё направление. Если $\alpha$ — отрицательное число ($\alpha<0$), то вектор меняет своё направление на противоположное.

## <center>Линейная комбинация векторов</center>

**Линейная комбинация** — это объединение операций сложения векторов и умножения на скаляр в одну. Каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются.

В *Python* линейная комбинация полностью соответствует своему названию и вычисляется как комбинация сложения векторов и умножения вектора на число.

In [9]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

Самое интересное в линейных комбинациях — это особые случаи, а именно **нулевая линейная комбинация**. Линейная комбинация векторов называется нулевой, если результат линейной комбинации равен нулевому вектору.

Как получить нулевой вектор из линейной комбинации? Самый простой вариант — чтобы все коэффициенты линейной комбинации были равны 0. Однако такой случай, называемый **тривиальным**, нам не интересен.

Нулевая линейная комбинация называется **нетривиальной**, если хотя бы один из коэффициентов отличен от 0.

Предположим, что нам удалось составить нетривиальную комбинацию, то есть удалось подобрать такие ${\omega }_i\neq 0$, что вектор $\overrightarrow{u}=\overrightarrow{0}$.

В таком случае векторы, из которых была составлена линейная комбинация $\overrightarrow{v_1},\ \overrightarrow{v_2},\ \dots ,\ \overrightarrow{v_n}$, называются **линейно зависимыми**.

Тогда хотя бы один из векторов, но не обязательно любой, в линейной комбинации можно выразить через другие векторы, представив его как линейную комбинацию.

Или же, возможно, как мы ни старались, но нам не удалось подобрать такие коэффициенты ${\omega }_i\neq 0$, чтобы составить нулевую нетривиальную линейную комбинацию. Такие векторы называются **линейно независимыми**. В таком случае ни один из векторов не выражается через другие векторы.

## <center>Скалярное произведение векторов</center>

Существует четыре способа умножить векторы между собой:

* Скалярное произведение. Результат — число. 
* Векторное произведение. Результат — вектор.
* Смешанное произведение. Результат — число. 
* Тензорное произведение. Результат — матрица.

Мы рассмотрим скалярное произведение.

Чтобы найти **скалярное произведение двух векторов**, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится.  

В *Python* скалярное произведение векторов вычисляется при помощи функции `np.dot()`:

In [10]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

Через скалярное произведение можно выразить длину вектора (обозначается как $\left|\overrightarrow{v}\right|$ или $|\left|\overrightarrow{v}\right||$).

В линейной алгебре **длина вектора** определяется как квадратный корень из скалярного произведения вектора с самим собой.

Длина вектора всегда неотрицательна и показывает, как близок вектор к нулевому.

Скалярное произведение — это не просто удобная форма записи умножения векторов. На самом деле скалярное произведение обладает рядом очень полезных **свойств**.

1) Линейность.

2) Скалярное произведение двух векторов $\overrightarrow{v_1}$ и $\overrightarrow{v_2}$ в точности равно произведению длин этих векторов $\left|\overrightarrow{v_1}\mathrm{\ }\right|$ и $\left|\overrightarrow{v_2}\mathrm{\ }\right|$ на косинус угла между ними $\mathrm{cos}\mathrm{}(\overrightarrow{v_1},\ \overrightarrow{v_2})$.

3) Из последнего свойства следует ещё одно свойство скалярного произведения. Если скалярное произведение двух векторов равно 0, то вектора ортогональны (находятся под углом 90°). И наоборот: если вектора ортогональны друг другу, их скалярное произведение равно 0.

## <center>Векторная запись линейной регрессии</center>

$$\hat{y}={\omega }_0+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$$

Давайте добавим коэффициент 1 перед параметром $\omega_0$:

$$\hat{y}={\omega }_01+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$$

А теперь представим параметры модели в виде вектора $\overrightarrow{\omega }$ и признаки — в виде вектора $\overrightarrow{x}$:

$$\overrightarrow{\omega }=\left( \begin{array}{c} {\omega }_0 \\ {\omega }_1 \\ {\omega }_2 \\ \dots \\ {\omega }_m \end{array} \right)\ \textrm{и}\ \overrightarrow{x}=\left( \begin{array}{c} 1 \\ x_1 \\ x_2 \\ \dots \\ x_m \end{array} \right)$$

Тогда уравнение линейной регрессии можно записать в лаконичной векторной форме скалярного произведения двух векторов $\overrightarrow{\omega }$ и $\overrightarrow{x}$:

$$\hat{y}=\overrightarrow{\omega }\cdot \overrightarrow{x}$$